// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace HackerInPyjamasML.Model
{
    public class ModelInput
    {
        [ColumnName("Sentences"), LoadColumn(0)]
        public string Sentences { get; set; }


        [ColumnName("Result"), LoadColumn(1)]
        public string Result { get; set; }


    }
}
